### ISSUE TITLE
wait less

### ISSUE THREAD

**Issue by kFTY** [flufy3d/CoinexMiner#2]
I do it this way, so I don't have to wait a partially closed order very long. For your consideration.
change:
`if elapsed_time > 60*config.wait_order:`

to
`if elapsed_time > 60*config.wait_order*float(data['left_amout'])/float(data['amout'])/:`

**Comment by flufy3d** [comment]
Thanks for your advice.
but I think make this parameter clear is good for great majority.
let them Let  themselves decide how long to wait.
